name: Build Documentation

on:
  push:
    branches:
      - main


jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: making-games-with-ai-course
      package_name: ml-games-course
      path_to_docs: making-games-with-ai-course/units/
      additional_args: --not_python_module
      languages: en
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
